name: macOS

on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    paths-ignore:
      - README.md

  # Run tests for any PRs.
  pull_request:
    branches:
      - master

    paths-ignore:
      - README.md

env:
  GITHUB_ORG_AND_REPO: "${{ github.repository }}"

jobs:
  build:
    runs-on: macos-10.15
    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip')) ||
      github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2

      - name: Build YugabyteDB third-party dependencies
        run: |
          brew install autoconf automake
          sudo mkdir -p /opt/yb-build/{thirdparty,brew,tmp}
          sudo chmod 777 /opt/yb-build/{thirdparty,brew,tmp}
          ./build_and_release.sh
